version: "3.7"

services:

  flask:
    build: ./flask
    container_name: flask
    volumes:
      - "/opt/docker/flask/webapp.db:/app/app/webapp.db"
    restart: unless-stopped
    expose:
      - 8080

  nginx:
    build: ./nginx
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80

